CREATE TABLE IF NOT EXISTS Comps(
    id int AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(240) not null,
    duration int DEFAULT 3,
    expires TIMESTAMP DEFAULT (DATE_ADD(CURRENT_TIMESTAMP, INTERVAL duration DAY)),
    current_reward int DEFAULT (starting_reward),
    starting_reward int DEFAULT 1,
    join_fee int DEFAULT 1,
    current_participants int DEFAULT 0,
    min_participants int DEFAULT 2,
    paid_out TINYINT(1) DEFAULT 0,
    did_calc TINYINT(1) DEFAULT 0,
    min_score int DEFAULT 1,
    first_place_per int,
    second_place_per int,
    third_place_per int,
    cost_to_create int DEFAULT 1,
    created_by int,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    FOREIGN KEY(created_by) REFERENCES Users(id),
    FOREIGN KEY(first_place_per) REFERENCES Users(id),
    FOREIGN KEY(second_place_per) REFERENCES Users(id),
    check (min_score >= 1),
    check (starting_reward >= 1),
    check (current_reward >= starting_reward),
    check (min_participants >= 2),
    check (current_participants >= 0),
    check(join_fee >= 0)
)